### ISSUE TITLE
/site-packages/knn_cuda/csrc/_ext/knn/knn.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by chalth** [omron-sinicx/EdgeSelectiveFeatureWeaving#1]
Hi,  when i run    ' python lit_corrnet3d_ESFW.py --batch_size=10 --data_dir=./trainset.h5 --test_data_dir=./testset.h5 --num_gpus 0'
the following errors occurs, do you know the reason? Thanks!

Traceback (most recent call last):
  File "lit_corrnet3d_ESFW.py", line 13, in <module>
    from knn_cuda import KNN 
  File "/home/ch/anaconda3/envs/regtr/lib/python3.8/site-packages/knn_cuda/__init__.py", line 38, in <module>
    _knn = load_cpp_ext("knn")
  File "/home/ch/anaconda3/envs/regtr/lib/python3.8/site-packages/knn_cuda/__init__.py", line 26, in load_cpp_ext
    ext = load(
  File "/home/ch/anaconda3/envs/regtr/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1080, in load
    return _jit_compile(
  File "/home/ch/anaconda3/envs/regtr/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1318, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/ch/anaconda3/envs/regtr/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1701, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: /home/ch/anaconda3/envs/regtr/lib/python3.8/site-packages/knn_cuda/csrc/_ext/knn/knn.so: cannot open shared object file: No such file or directory

**Comment by eashratj** [comment]
> Hi, when i run ' python lit_corrnet3d_ESFW.py --batch_size=10 --data_dir=./trainset.h5 --test_data_dir=./testset.h5 --num_gpus 0' the following errors occurs, do you know the reason? Thanks!
> 
> Traceback (most recent call last): File "lit_corrnet3d_ESFW.py", line 13, in from knn_cuda import KNN File "/home/ch/anaconda3/envs/regtr/lib/python3.8/site-packages/knn_cuda/**init**.py", line 38, in _knn = load_cpp_ext("knn") File "/home/ch/anaconda3/envs/regtr/lib/python3.8/site-packages/knn_cuda/**init**.py", line 26, in load_cpp_ext ext = load( File "/home/ch/anaconda3/envs/regtr/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1080, in load return _jit_compile( File "/home/ch/anaconda3/envs/regtr/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1318, in _jit_compile return _import_module_from_library(name, build_directory, is_python_module) File "/home/ch/anaconda3/envs/regtr/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1701, in _import_module_from_library module = importlib.util.module_from_spec(spec) ImportError: /home/ch/anaconda3/envs/regtr/lib/python3.8/site-packages/knn_cuda/csrc/_ext/knn/knn.so: cannot open shared object file: No such file or directory

It's because of the incorrect build of _knn_cuda_ library as a result the compiled extension of _knn_cuda_ which is the knn.so file is missing! For me this error occurred due to version and package mismatch between pytorch & cuda, Compatible pytorch and cuda version solved this error for me!
